export const ROUTES = {
  HOME: '/',
  JOURNEY: '/journey',
  SNEAK_PEEK: '/sneak-peek',
  ADORE: '/adore',
  MOMENTS: '/moments',
  NOTES_365: '/365-notes',
  OPEN_WHEN: '/open-when',
  WISHES: '/wishes',
  SECRET_VAULT: '/secret-vault',
  WHAT_AM_I_TO_YOU: '/what-am-i-to-you',
  REFLECTIONS: '/reflections',
  BTS: '/bts',
  SETTINGS: '/settings',
  NOTIFICATIONS: '/notifications',
  ADMIN: '/admin',
} as const;
